version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  kafdrop:
    image: 'obsidiandynamics/kafdrop'
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - zookeeper
      - kafka
  postgres:
    image: 'debezium/example-postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=debezium
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - zookeeper
      - kafka  
  debezium-connect:
    image: 'debezium/connect'
    ports:
      - '8083:8083'
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
      - HEAP_OPTS=-Xms256M -Xmx256M
      - ADVERTISED_HOST_NAME=debezium-connect
 #     - ADVERTISED_HOST_NAME=$(echo $DOCKER_HOST | cut -f3  -d'/' | cut -f1 -d':')
    depends_on:
      - zookeeper
      - kafka  
      - postgres
  debezium-ui:
    image: 'debezium/debezium-ui'
    ports:
      - '8088:8080'
    environment:
      - KAFKA_CONNECT_URIS=http://debezium-connect:8083
    depends_on:
      - debezium-connect
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.16.1'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512M -Xmx512M
    depends_on:
      - debezium-connect
  kibana:
    image: 'kibana:7.16.1'
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - debezium-connect
      - elasticsearch
